create table if not exists pedidos(
    id int UNSIGNED NOT NULL AUTO_INCREMENT,
    mesaId INT UNSIGNED NULL DEFAULT NULL,
    mozo_id INT UNSIGNED NULL DEFAULT NULL,
    direccion VARCHAR(60) NULL DEFAULT NULL,
    estado VARCHAR(10) DEFAULT 'EN CURSO',
    creadoEl TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizadoEl TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(mesaId) REFERENCES mesas(id),
    FOREIGN KEY(mozo_id) REFERENCES usuarios(id),
    PRIMARY KEY(id)
);